
spring:
    datasource:
      url: jdbc:mysql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
      usename: root
      password: Thaisebruno10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

